//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_project_Main/InputSystem/TouchControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchControls"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""553f0b80-3a48-4378-9b8c-b94f26bd9533"",
            ""actions"": [
                {
                    ""name"": ""FirstFingerHold"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3dd35f6c-e992-41f8-bfd5-b88ccf0f99f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstFingerDeltaPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a0dc1a34-ed49-4661-83ac-7d1c76fc0420"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstFinger2dPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e8a958db-22a4-4ad6-9b86-8a802a915cd0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondFingerHold"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8ba8f7b-00b6-4690-8771-9498a3a06e92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""db59230b-3d72-42f0-aa3f-3a9757ee1ed4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondFinger2dPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f6776b82-c0c5-4e6e-a100-1406c6c268eb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a2fb8ac-02c9-4985-b6fd-dbcb9cd7309e"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstFingerHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3925491b-7aa0-4940-b2ac-0401225486e4"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstFingerDeltaPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9149016-8895-40ad-88bd-51bfa3f9781b"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondFingerHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d3f50f2-41ea-431b-8834-9c07e8a53836"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""675a4e76-5328-4687-a886-99ea94571d5c"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstFinger2dPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9882771-30b8-43d0-9417-1af7ce368705"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondFinger2dPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_FirstFingerHold = m_Touch.FindAction("FirstFingerHold", throwIfNotFound: true);
        m_Touch_FirstFingerDeltaPosition = m_Touch.FindAction("FirstFingerDeltaPosition", throwIfNotFound: true);
        m_Touch_FirstFinger2dPosition = m_Touch.FindAction("FirstFinger2dPosition", throwIfNotFound: true);
        m_Touch_SecondFingerHold = m_Touch.FindAction("SecondFingerHold", throwIfNotFound: true);
        m_Touch_SecondFingerPosition = m_Touch.FindAction("SecondFingerPosition", throwIfNotFound: true);
        m_Touch_SecondFinger2dPosition = m_Touch.FindAction("SecondFinger2dPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_FirstFingerHold;
    private readonly InputAction m_Touch_FirstFingerDeltaPosition;
    private readonly InputAction m_Touch_FirstFinger2dPosition;
    private readonly InputAction m_Touch_SecondFingerHold;
    private readonly InputAction m_Touch_SecondFingerPosition;
    private readonly InputAction m_Touch_SecondFinger2dPosition;
    public struct TouchActions
    {
        private @TouchControls m_Wrapper;
        public TouchActions(@TouchControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstFingerHold => m_Wrapper.m_Touch_FirstFingerHold;
        public InputAction @FirstFingerDeltaPosition => m_Wrapper.m_Touch_FirstFingerDeltaPosition;
        public InputAction @FirstFinger2dPosition => m_Wrapper.m_Touch_FirstFinger2dPosition;
        public InputAction @SecondFingerHold => m_Wrapper.m_Touch_SecondFingerHold;
        public InputAction @SecondFingerPosition => m_Wrapper.m_Touch_SecondFingerPosition;
        public InputAction @SecondFinger2dPosition => m_Wrapper.m_Touch_SecondFinger2dPosition;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @FirstFingerHold.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerHold;
                @FirstFingerHold.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerHold;
                @FirstFingerHold.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerHold;
                @FirstFingerDeltaPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerDeltaPosition;
                @FirstFingerDeltaPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerDeltaPosition;
                @FirstFingerDeltaPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerDeltaPosition;
                @FirstFinger2dPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFinger2dPosition;
                @FirstFinger2dPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFinger2dPosition;
                @FirstFinger2dPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFinger2dPosition;
                @SecondFingerHold.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerHold;
                @SecondFingerHold.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerHold;
                @SecondFingerHold.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerHold;
                @SecondFingerPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFinger2dPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFinger2dPosition;
                @SecondFinger2dPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFinger2dPosition;
                @SecondFinger2dPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFinger2dPosition;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FirstFingerHold.started += instance.OnFirstFingerHold;
                @FirstFingerHold.performed += instance.OnFirstFingerHold;
                @FirstFingerHold.canceled += instance.OnFirstFingerHold;
                @FirstFingerDeltaPosition.started += instance.OnFirstFingerDeltaPosition;
                @FirstFingerDeltaPosition.performed += instance.OnFirstFingerDeltaPosition;
                @FirstFingerDeltaPosition.canceled += instance.OnFirstFingerDeltaPosition;
                @FirstFinger2dPosition.started += instance.OnFirstFinger2dPosition;
                @FirstFinger2dPosition.performed += instance.OnFirstFinger2dPosition;
                @FirstFinger2dPosition.canceled += instance.OnFirstFinger2dPosition;
                @SecondFingerHold.started += instance.OnSecondFingerHold;
                @SecondFingerHold.performed += instance.OnSecondFingerHold;
                @SecondFingerHold.canceled += instance.OnSecondFingerHold;
                @SecondFingerPosition.started += instance.OnSecondFingerPosition;
                @SecondFingerPosition.performed += instance.OnSecondFingerPosition;
                @SecondFingerPosition.canceled += instance.OnSecondFingerPosition;
                @SecondFinger2dPosition.started += instance.OnSecondFinger2dPosition;
                @SecondFinger2dPosition.performed += instance.OnSecondFinger2dPosition;
                @SecondFinger2dPosition.canceled += instance.OnSecondFinger2dPosition;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnFirstFingerHold(InputAction.CallbackContext context);
        void OnFirstFingerDeltaPosition(InputAction.CallbackContext context);
        void OnFirstFinger2dPosition(InputAction.CallbackContext context);
        void OnSecondFingerHold(InputAction.CallbackContext context);
        void OnSecondFingerPosition(InputAction.CallbackContext context);
        void OnSecondFinger2dPosition(InputAction.CallbackContext context);
    }
}
